### ISSUE TITLE
Address Spotbugs errors

### ISSUE THREAD

**Issue by pierre** [killbill/killbill-plugin-api#18]
1. Enforce the Spotbugs checks by enabling the property `check.fail-spotbugs`
2. Address the errors.

**Comment by xsalefter** [comment]
I tried to find following lines in `killbill-plugin-api` project:

- check.fail-spotbugs
- "spotbugs"
- "findbugs"
- check.fail-spotbugs

and cannot found anything. So, I will close this.

**Comment by xsalefter** [comment]
Ok, forgot about `check.fail-spotbugs` should be `true`.

**Comment by pierre** [comment]
Indeed: the default is `false` in the parent pom.xml since we have a long way to go until all of our projects can pass all checks.

**Comment by xsalefter** [comment]
I'll close this now.
